/**
 * Promomash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserCommand } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param username 
     * @param password 
     */
    authLogin(username?: string, password?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param body 
     */
    authLogout(body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createUserCommand 
     */
    authRegister(createUserCommand: CreateUserCommand, extraHttpRequestParams?: any): Observable<{}>;

}
