/**
 * Promomash
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangeNameCommand } from '../model/models';
import { CreateCountryCommand } from '../model/models';
import { GetCountriesQueryResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CountryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param changeNameCommand 
     */
    countryChangeName(changeNameCommand: ChangeNameCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createCountryCommand 
     */
    countryCreate(createCountryCommand: CreateCountryCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    countryDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    countryGet(id: string, extraHttpRequestParams?: any): Observable<GetCountriesQueryResponse>;

    /**
     * 
     * 
     */
    countryGetCountries(extraHttpRequestParams?: any): Observable<Array<GetCountriesQueryResponse>>;

}
